src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Correct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TR_AnsweredQuestion.cls
public class TR_AnsweredQuestion {

    @AuraEnabled
    public String question { get; set; }
    @AuraEnabled
    public Boolean correct { get; set; }
    @AuraEnabled
    public String id { get; set; }

    public TR_AnsweredQuestion() {
    }

    public TR_AnsweredQuestion(AnsweredQuestion__c question) {
        this.id = question.Id;
        this.question = question.Question__r.Question__c;
        this.correct = question.Correct__c;
    }

    public static List<TR_AnsweredQuestion> mapToAnsweredQuestions(List<AnsweredQuestion__c> questions) {
        List<TR_AnsweredQuestion> result = new List<TR_AnsweredQuestion>();
        for (AnsweredQuestion__c question : questions) {
            TR_AnsweredQuestion tmp = new TR_AnsweredQuestion(question);
            result.add(tmp);
        }
        return result;
    }
}