src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Correct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aura</fullName>
                </value>
                <value>
                    <fullName>Fields</fullName>
                </value>
                <value>
                    <fullName>Limits</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>MC Scripts</fullName>
                </value>
                <value>
                    <fullName>MC APIs</fullName>
                </value>
                <value>
                    <fullName>MC Data Management</fullName>
                </value>
                <value>
                    <fullName>MC Admin</fullName>
                </value>
                <value>
                    <fullName>MC Marketing</fullName>
                </value>
                <value>
                    <fullName>Interview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Presentations</fullName>
                </value>
                <value>
                    <fullName>First Application</fullName>
                </value>
                <value>
                    <fullName>Second Application</fullName>
                </value>
                <value>
                    <fullName>MC Specialist</fullName>
                </value>
                <value>
                    <fullName>MC Consultant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TR_Question.cls
public class TR_Question {
    @AuraEnabled
    public String id { get; set; }
    @AuraEnabled
    public String question { get; set; }
    @AuraEnabled
    public String answer { get; set; }
    @AuraEnabled
    public String category { get; set; }
    @AuraEnabled
    public String stage { get; set; }
    @AuraEnabled
    public String answeredBy { get; set; }
    @AuraEnabled
    public Boolean isAnswerCorrect { get; set; }

    public TR_Question() {
    }

    public TR_Question(Question__c question) {
        this.id = question.Id;
        this.question = question.Question__c;
        this.answer = question.Answer__c;
        this.category = question.Category__c;
        this.stage = question.Stage__c;
    }

    public TR_Question(AnsweredQuestion__c answeredQuestion) {
        this.id = answeredQuestion.Question__r.Id;
        this.question = answeredQuestion.Question__r.Question__c;
        this.answer = answeredQuestion.Id;
        this.category = answeredQuestion.Question__r.Category__c;
        this.stage = answeredQuestion.Question__r.Stage__c;
        this.answeredBy = answeredQuestion.Contact__c;
        this.isAnswerCorrect = answeredQuestion.Correct__c;
    }

    public static List<TR_Question> mapToTrQuestions(List<AnsweredQuestion__c> answeredQuestions) {
        List<TR_Question> trQuestions = new List<TR_Question>();
        for (AnsweredQuestion__c answeredQuestion : answeredQuestions) {
            TR_Question trQuestion = new TR_Question(answeredQuestion);
            trQuestions.add(trQuestion);
        }
        return trQuestions;
    }
}