src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TR_Game.cls
public class TR_Game {
    @AuraEnabled
    public String id { get; set; }
    @AuraEnabled
    public String type { get; set; }
    @AuraEnabled
    public Decimal duration { get; set; }
    @AuraEnabled
    public List<TR_Question> questions { get; set; }
    @AuraEnabled
    public List<TR_Participant> participants { get; set; }
    @AuraEnabled
    public Datetime createdTime { get; set; }

    public TR_Game() {
    }

    public TR_Game(Game__c game) {
        this.id = game.Id;
        this.type = game.Type__c;
        this.duration = game.Duration__c;
    }

    public static TR_Game createFullObject(Game__c game) {
        TR_Game trGame = new TR_Game();
        trGame.id = game.Id;
        trGame.type = game.Type__c;
        trGame.duration = game.Duration__c;
        trGame.createdTime = game.CreatedDate;
        trGame.questions = TR_Question.mapToTrQuestions(game.AnsweredQuestions__r);
        Set<Contact> contacts = getContactsWithoutDuplicates(game);
        trGame.participants = TR_Participant.mapToParticipants(new List<Contact>(contacts));
        return trGame;
    }

    private static Set<Contact> getContactsWithoutDuplicates(Game__c game) {
        Set<Contact> contacts = new Set<Contact>();
        for (AnsweredQuestion__c answeredQuestion : game.AnsweredQuestions__r) {
            contacts.add(answeredQuestion.Contact__r);
        }
        return contacts;
    }

    public static List<TR_Game> mapToTrGames(List<Game__c> games) {
        List<TR_Game> trGames = new List<TR_Game>();
        for (Game__c game : games) {
            trGames.add(createFullObject(game));
        }
        return trGames;
    }
}