src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TR_ContactsSelector.cls
public with sharing class TR_ContactsSelector {

    public static List<Contact> selectContactById(String contactId) {
        return [
                SELECT Email, Id
                FROM Contact
                WHERE Id = :contactId
        ];
    }

    public static List<Contact> selectAllContacts() {
        return [
                SELECT Id, Name, Email
                FROM Contact
                ORDER BY Name
        ];
    }

    public static List<Contact> selectContactsByName(String name) {
        String query = name + '%';
        return [
                SELECT Id, (SELECT Id, Game__c FROM AnsweredQuestions__r)
                FROM Contact
                WHERE Name LIKE :query
        ];
    }
}