src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Correct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Game__c.object
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aura</fullName>
                </value>
                <value>
                    <fullName>Fields</fullName>
                </value>
                <value>
                    <fullName>Limits</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>MC Scripts</fullName>
                </value>
                <value>
                    <fullName>MC APIs</fullName>
                </value>
                <value>
                    <fullName>MC Data Management</fullName>
                </value>
                <value>
                    <fullName>MC Admin</fullName>
                </value>
                <value>
                    <fullName>MC Marketing</fullName>
                </value>
                <value>
                    <fullName>Interview</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Presentations</fullName>
                </value>
                <value>
                    <fullName>First Application</fullName>
                </value>
                <value>
                    <fullName>Second Application</fullName>
                </value>
                <value>
                    <fullName>MC Specialist</fullName>
                </value>
                <value>
                    <fullName>MC Consultant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TR_AnsweredQuestionsSelector.cls
public with sharing class TR_AnsweredQuestionsSelector {

    public static List<AnsweredQuestion__c> selectAnsweredQuestionsByGameAndParticipant(String gameId, String participantId) {
        return [
                SELECT Id, Question__r.Id, Question__r.Question__c, Question__r.Category__c, Question__r.Stage__c,
                        Contact__c, Correct__c, Question__r.Answer__c
                FROM AnsweredQuestion__c
                WHERE Game__c = :gameId AND Contact__c = :participantId
        ];
    }

    public static Set<String> selectGamesIdsWithoutAnsweredQuestions() {
        List<AggregateResult> aggregateResults = [
                SELECT Game__r.Id, COUNT(Id)
                FROM AnsweredQuestion__c
                GROUP BY Game__r.Id
                HAVING COUNT(Id) = 0
        ];
        Set<String> gamesIds = new Set<String>();
        for (AggregateResult aggregateResult : aggregateResults) {
            gamesIds.add(aggregateResult.Id);
        }
        return gamesIds;
    }
}