src/objects/AnsweredQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Game__c</fullName>
        <label>Game</label>
        <referenceTo>Game__c</referenceTo>
        <relationshipLabel>AnsweredQuestions</relationshipLabel>
        <relationshipName>AnsweredQuestions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AnsweredQuestion</label>
    <nameField>
        <label>AnsweredQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AnsweredQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Questions</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TR_GameService.cls
public with sharing class TR_GameService {

    @AuraEnabled
    public static TR_Game createGame(String type, Decimal duration) {
        Game__c game = new Game__c();
        game.Archived__c = false;
        game.Duration__c = duration;
        game.Type__c = type;
        insert game;
        return new TR_Game(game);
    }

    @AuraEnabled
    public static void finishGame(String gameId) {
        Game__c game = new Game__c();
        game.Id = gameId;
        game.Archived__c = true;
        update game;
    }

    @AuraEnabled(Cacheable = true)
    public static Integer countGamesBetweenPlayers(List<String> playersIds) {
        List<Game__c> allGamesWithTheseIds = [
                SELECT Id, (SELECT Id, Contact__r.Name, Contact__r.Id FROM AnsweredQuestions__r WHERE Contact__r.Id IN :playersIds)
                FROM Game__c
        ];
        Integer result = 1;
        for (Game__c game : allGamesWithTheseIds) {
            Set<String> participantsIds = new Set<String>();
            for (AnsweredQuestion__c ansQu : game.AnsweredQuestions__r) {
                participantsIds.add(ansQu.Contact__r.Id);
            }
            if (participantsIds.size() == 2) {
                result++;
            }
        }
        return result;
    }
}